name = 'office-user-auto-create'
account_id = ''
type = 'webpack'
workers_dev = true
webpack_config = 'webpack.config.js'

[vars]
_ANNOUNCEMENT = 'some announcement'
_GET_CODE_LINK = 'https://some.link'
_AAD_CONFIG = '{ "tenantId": "f2a172f5-a652-4c14-ab82-534fea579c70", "clientId": "d5ac6d49-f701-40a6-b422-2952f1351c2d", "clientSecret": "1ZS~L39V1L.M5W6M5Mkkouie.dx.vGu.vk" }'
_OFFICE_DOMAINS = '["effinghamhighschool.com"]'
_OFFICE_SUBSCRIPTIONS = '[{ "name": "Office 365 A1 学生版", "sku": "314c4481-f395-4525-be8b-2ec4bb1e9d91" }, { "name": "Office 365 A1 教职员工版", "sku": "94763226-9b3c-4e75-a931-5c89701abe66" },{ "name": "面向学生的 Office 365 A1 Plus", "sku": "e82ae690-a2d5-4d76-8d30-7c6e01e6022e" }, { "name": "面向教职员工的 Office 365 A1 Plus", "sku": "78e66a63-337a-4a9a-8959-41c6654dfb56" }]'
_USERNAME_BLACKLIST = '["admin", "gay"]'
_GENERATE_CODES_PATH_SECRET = '/office'
